disable TMA and warp_specialization on A100
Summary:
1. Disable warp_specialization and TMA on A100.
2. Enable UT for mrn kernels on A100.

Background:

Previously we may get this error when running grouped_gemm and jagged_jagged_bmm_split_k on A100:
```
Traceback (most recent call last):
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/hammer/modules/sequential/encoders/tests/fused_hstu_test.py", line 948, in test_mrn_train_parity
    self._test_mrn_parity(*args, **kwargs, is_train=True)
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/hammer/modules/sequential/encoders/tests/fused_hstu_test.py", line 1153, in _test_mrn_parity
    test_y.sum().backward()
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/torch/_tensor.py", line 648, in backward
    torch.autograd.backward(
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/torch/autograd/__init__.py", line 354, in backward
    _engine_run_backward(
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/torch/autograd/graph.py", line 829, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/torch/autograd/function.py", line 308, in apply
    return user_fn(self, *args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/fast_moe/kernels/triton/triton_moe.py", line 536, in backward
    d_jagged = IndexSelectJaggedBmm._calc_d_jagged(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/fast_moe/kernels/triton/triton_moe.py", line 583, in _calc_d_jagged
    d_jagged_expanded = grouped_gemm(
                        ^^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/fast_moe/kernels/triton/grouped_gemm.py", line 990, in grouped_gemm
    return _grouped_gemm(
           ^^^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/fast_moe/kernels/triton/grouped_gemm.py", line 954, in _grouped_gemm
    fn[grid](
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/triton/runtime/jit.py", line 368, in <lambda>
    return lambda *args, **kwargs: self.run(
                                   ^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/fast_moe/kernels/triton/utils.py", line 158, in run
    ret = super().run(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/triton/runtime/autotuner.py", line 354, in run
    ret = self.fn.run(
          ^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/triton/runtime/jit.py", line 830, in run
    kernel = self.compile(
             ^^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/triton/fb/triton_util.py", line 238, in new_compile
    return _compiler.compile(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/triton/fb/triton_util.py", line 210, in compile
    return self.orig_compile(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/triton/compiler/compiler.py", line 439, in compile
    src, metadata_group, hash = compile_fn(src, target, options, autotune)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/triton/compiler/compiler.py", line 382, in compile_fn
    next_module = compile_ir(module, metadata)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/triton/backends/nvidia/compiler.py", line 464, in <lambda>
    stages["cubin"] = lambda src, metadata: self.make_cubin(
                                            ^^^^^^^^^^^^^^^^
  File "/re_cwd/buck-out/v2/gen/fbcode/34345606d54e9f53/hammer/modules/sequential/encoders/tests/__fused_hstu_test__/fused_hstu_test#link-tree/triton/backends/nvidia/compiler.py", line 432, in make_cubin
    raise PTXASError(f"Internal Triton PTX codegen error:
{log}")
triton.runtime.errors.PTXASError: PTXAS error: Internal Triton PTX codegen error:
ptxas /re_tmp/tmp9x0s7gcs.ptx, line 368; error   : Feature 'elect' requires .target sm_90 or higher
ptxas /re_tmp/tmp9x0s7gcs.ptx, line 456; error   : Feature 'mbarrier.arrive.expect_tx' requires .target sm_90 or higher
ptxas /re_tmp/tmp9x0s7gcs.ptx, line 463; error   : Feature 'cp.async.bulk.tensor' requires .target sm_90 or higher
ptxas /re_tmp/tmp9x0s7gcs.ptx, line 463; error   : Feature '.mbarrier::complete_tx::bytes' requires .target sm_90 or higher
ptxas /re_tmp/tmp9x0s7gcs.ptx, line 469; error   : Feature 'cp.async.bulk.tensor' requires .target sm_90 or higher
ptxas /re_tmp/tmp9x0s7gcs.ptx, line 469; error   : Feature '.mbarrier::complete_tx::bytes' requires .target sm_90 or higher
ptxas /re_tmp/tmp9x0s7gcs.ptx, line 493; error   : Feature 'mbarrier.try_wait.parity' requires .target sm_90 or higher
ptxas /re_tmp/tmp9x0s7gcs.ptx, line 1951; error   : Feature 'mbarrier.arrive.expect_tx' requires .target sm_90 or higher
ptxas /re_tmp/tmp9x0s7gcs.ptx, line 1957; error   : Feature 'cp.async.bulk.tensor' requires .target sm_90 or higher
ptxas /re_tmp/tmp9x0s7gcs.ptx, line 1957; error   : Feature '.mbarrier::complete_tx::bytes' requires .target sm_90 or higher
ptxas /re_tmp/tmp9x0s7gcs.ptx, line 1962; error   : Feature 'cp.async.bulk.tensor' requires .target sm_90 or higher
ptxas /re_tmp/tmp9x0s7gcs.ptx, line 1962; error   : Feature '.mbarrier::complete_tx::bytes' requires .target sm_90 or higher
ptxas fatal   : Ptx assembly aborted due to errors
```

Reviewed By: y-sq

Differential Revision: D74635146

fbshipit-source-id: 8ccc82101abc843a9e23c8f63f0f42d710b3e586